### ISSUE TITLE
Revoke expired content from APP (delete from IndexedDB)

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#172]
look at socketConnection.ts

**Comment by laurensgroeneveld** [comment]
@ivanslabbert Looking at this with Johan, I see two ways to go:
- Delete when receiving `data` in the socketConnection (was thinking about this because you say look at socketConnection)
- Continously check in the background (say, every minute) if something is expired and remove it.

The latter might be a bit more expensive computationally, so not sure if you thought about which way to go?

**Comment by belljohan3** [comment]
Hi @ivanslabbert ! Can you have a look to the comment above ?

**Comment by ivanslabbert** [comment]
> @ivanslabbert Looking at this with Johan, I see two ways to go:
> - Check for posts/tags to delete when receiving `data` in the socketConnection (was thinking about this because you say look at socketConnection)
> - Continously check in the background (say, every minute) if something is expired and remove it.
> 
> The latter might be a bit more expensive computationally, so not sure if you thought about which way to go?

I think for now checking on connection is sufficient. The app will disconnect from time to time and on reconnection data will be cleared. Adding a scheduler later is an option if there are data security concerns.
