### ISSUE TITLE
Shared, API: Clear draft and expired docs from IndexedDB in non-cms mode, and exclude from data from API to Client

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#281]

**Comment by DirkDevelopmentFreelance** [comment]
Need to implement delete functionality before working with the drafted docs.

**Comment by laurensgroeneveld** [comment]
The test in [EditContent.spec.ts](https://github.com/bccsa/luminary/pull/304/files#diff-ca9cb683400f01fedcf97a45392f2ba88ae8da4bead6cf34b5cc80ad511d3154) is failing. I found it's always the _first_ test in the file that fails: putting a different test from that file on top makes that test fail. It's not the specific test that's the problem (and actually we can see that because that test `can load content from the database` is exactly the same as a test lower in the file `renders the title of the default language` which is succeeding).
