### ISSUE TITLE
Display categories & related content with image/title next to posts

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#318]
Instead of displaying "tags" as a text list, display all tags a video belongs to in the same horizontal scrollable viewer as on the homepage.

## Acceptance criteria
- Remove the current Tags below the content
- Show a scrollable viewer for all tags
- Highlight the current video so it's clear that it's selected

## Technical notes
On how to higlight the current item: Take the hover style as a starting point. Probably the image also needs to be "highlighted", by making it either transparent or have a dark overlay. Both are easily achieved with CSS, research a bit on how to do it.

**Comment by belljohan3** [comment]
- [ ] Display HorizontalScrollableTagViewer only for topics, exclude the posts itself
- [ ] Display Vertical layout for categories, highlight the post itself, order by publish date
- [ ] [VERTICAL LAYOUT] if there is only one post, it should be hidden
- [ ] Shows the horizontal layout below the vertical one.

**Comment by ivanslabbert** [comment]
![Image](https://github.com/user-attachments/assets/ed915bb0-e71b-45c3-aa4d-3d45e81757d0)

**Comment by ivanslabbert** [comment]
From the discussion at the standup meeting today:


![Image](https://github.com/user-attachments/assets/35f6c26f-8da7-4a27-b7a3-57a58d296151)

**Comment by laurensgroeneveld** [comment]
Other notes from the standup: ensure there is enough space between the article and the categories, so the article remains the focus (this is something ActiveChristianity also doesn't do well). The article should always use more of the screen than the category switcher. Switch at an earlier breakpoint to display the categories below the content (in the current demo at smaller screens it was 50% article and 50% categories).

**Comment by laurensgroeneveld** [comment]
Feedback from the standup:
- LG: Some concerns about the tab switcher, but we'll leave it like this for now because we don't expect a lot of posts with multiple categories. In the future we could pass the clicked category in a query parameter so we can select the right one by default (but not needed right now).
- Put the categories to the side of the post on larger screens, [like ActiveChristianity](https://activechristianity.org/righteous-judgment-and-evil-judgment-salvation-and-destruction)
- Put a light gray background behind the related content, to make it more visually stand out
