### ISSUE TITLE
CMS: Add SEO title and summary fields to EditContent

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#417]
Fields are already in the data model and API, but needs to be implemented in the CMS editor and as metadata in the app.

**Comment by laurensgroeneveld** [comment]
I left a [review](https://github.com/bccsa/luminary/pull/427#pullrequestreview-2379362205) with some ideas on how to improve on the UX of this. Of course, this could also be done in a follow-up PR - but I just want to stress that I think we need to be careful about adding too much fields/complexity to the interface so that editors are not overwhelmed again when they switch to the new system 🙂
