### ISSUE TITLE
APP: Add SEO title and summary fields to SingleContent

### ISSUE THREAD

**Issue by ivanslabbert** [bccsa/luminary#432]
See #417

**Comment by belljohan3** [comment]
Hey @ivanslabbert 

After some research, i found `vueuse/head`. It is compatible with vue3, version we are using for this project. instead of having a separate field for SEO (seoTitle, seoString), we can directly use the title and summary for the current content. That will also help by simplifying things for the Editors. Or, the seoTitle and seoString can use the. title and summary values of the current content. Then in that way, we don't have to show or allow the editors to edit those fields.

I hope i am understandable 👍

**Comment by ivanslabbert** [comment]
> Hey @ivanslabbert
> 
> After some research, i found `vueuse/head`. It is compatible with vue3, version we are using for this project. instead of having a separate field for SEO (seoTitle, seoString), we can directly use the title and summary for the current content. That will also help by simplifying things for the Editors. Or, the seoTitle and seoString can use the. title and summary values of the current content. Then in that way, we don't have to show or allow the editors to edit those fields.
> 
> I hope i am understandable 👍

We need both options. In cases where it is not set, the default title and summary should be used. Where the SEO fields are set, they should be used. In many cases (for public content) the SEO fields are necessary as this is what will be indexed for google or other search engine searches, and the terms people use when searching might be different from what the editors want as the title and summary that is displayed in the app / website.

**Comment by belljohan3** [comment]
- [ ] https://github.com/vueuse/head
- [ ] https://www.youtube.com/watch?v=qzkdP9z5DLY
